### ISSUE TITLE
wrong defination

### ISSUE THREAD

**Issue by igmominkhan** [mostafizurRahaman/typescript-technocrat#1]
in the basic data types, you have describe all the data types like this. 

String: We can implicitly define a type of a variable in typescript as string.

NOTE:- for implicit type correction typescript itself define types, that you have cleared on the implicit type defination. But on the above line you are talking about implicit type correction. Where it will be explicit type correction. 

Implicit type correction is defined by typescript and Explicit types are defined by programmer.

**Comment by mostafizurrahaman** [comment]
I will refactor the mistake. Thank you.
